- samples/desktop/CQELight.Examples.Console/CQELight.Examples.Console.csproj
- src/CQELight.DAL.EFCore/Bootstrapper.ext.cs
- src/CQELight.DAL.EFCore/CQELight.DAL.EFCore.csproj
- src/CQELight.DAL.EFCore/EFRepository.cs
- src/CQELight.TestFramework/BaseUnitTestClass.cs
- src/CQELight/IoC/DIManager.cs
- tests/CQELight.DAL.EFCore.Integration.Tests/Bootstrapper.ext.Tests.cs
- tests/CQELight.DAL.EFCore.Integration.Tests/EFRepository.Tests.cs
> fix ef core dal bugs

- src/CQELight/Dispatcher/CoreDispatcher.cs
- tests/CQELight.Integration.Tests/Dispatcher/CoreDispatcher.Integration.Tests.cs
> returns weakreference instance instead of reference

- src/CQELight.Buses.InMemory/Events/InMemoryEventBus.cs
- src/CQELight/Tools/Extensions/TypeExtensions.cs
- tests/CQELight.Buses.InMemory.Integration.Tests/InMemoryEventBus.Tests.cs
- tests/CQELight.Tests/Tools/Extensions/TypeExtensions.Tests.cs
> add some verification for subtypes

- src/CQELight.Buses.InMemory/Bootstrapper.ext.cs
- src/CQELight.DAL.EFCore/BaseDbContext.cs
- src/CQELight.DAL.EFCore/EFCoreAutoMapper.cs
- tests/CQELight.DAL.EFCore.Integration.Tests/DbEntities.cs
- tests/CQELight.DAL.EFCore.Integration.Tests/Migrations/20190319112507_IPersistableEntity-ComposedKey.Designer.cs
- tests/CQELight.DAL.EFCore.Integration.Tests/Migrations/20190319112507_IPersistableEntity-ComposedKey.cs
> allow IPersistableEntity to have composedKey

- src/CQELight/EventStore/BasicSnapshotBehaviorProvider.cs
- tests/CQELight.Tests/DAL/Common/ComposedKeyPersistableEntity.Tests.cs
- tests/CQELight.Tests/DAL/Common/CustomKeyPersistableEntity.Tests.cs
- tests/CQELight.Tests/EventStore/BasicSnapshotBehaviorProvider.cs
- tests/CQELight.Tests/EventStore/Behaviors/NumericSnapshotBehavior.Tests.cs
- tests/CQELight.Tests/Extensions/IEventSourcedAggregateExtensions.Tests.cs
> add some tests for CQELight base assembly

- benchmarks/CQELight_Benchmarks/Benchmarks/Buses/InMemoryEventBusBenchmark.cs
- benchmarks/CQELight_Benchmarks/Models/Buses/Events/TestDispatchEvent.cs
- benchmarks/CQELight_Benchmarks/Models/Buses/Events/TestDispatchEventHandler.cs
- benchmarks/CQELight_Benchmarks/Models/Buses/Events/TestDispatchEventHandler2.cs
- benchmarks/CQELight_Benchmarks/Models/Buses/Events/TestDispatchEventHandler3.cs
- src/CQELight.Buses.InMemory/Events/InMemoryEventBus.cs
- tests/CQELight.Buses.InMemory.Integration.Tests/InMemoryEventBus.Tests.cs
> add some tests and stabilizing

- src/CQELight.IoC.Microsoft.Extensions.DependencyInjection/Bootstrapper.ext.cs
- src/CQELight.IoC.Microsoft.Extensions.DependencyInjection/MicrosoftScope.cs
- src/CQELight/Tools/ObservableObject.cs
> review extension Microsoft DependencyInjection

- src/CQELight/Abstractions/DDD/AggregateRoot.cs
> optimization for aggregate event publishing

- src/CQELight.TestFramework/Extensions/DALExtensions.cs
> supports IPersistableEntity as base for TestFramework

- src/CQELight/DAL/Common/BasePersistableEntity.cs
> remove uppercases for stamps columns

- src/CQELight.DAL.MongoDb/Mapping/MappingInfo.cs
- src/CQELight.DAL.MongoDb/MongoRepository.cs
> fix some repository code for using IPersistableEntity

- src/CQELight/Bootstrapping/Bootstrapper.cs
- src/CQELight/Tools/CQELightToolbox.cs
- tests/CQELight.Tests/Bootstrapper/Bootstrapper.Tests.cs
> adding CQELight toolbox

- src/CQELight.Buses.RabbitMQ/Bootstrapper.ext.cs
- src/CQELight.Buses.RabbitMQ/RabbitMQClient.cs
- src/CQELight.DAL.MongoDb/CQELight.DAL.MongoDb.csproj
- tests/CQELight.Buses.RabbitMQ.Integration.Tests/Bootstrapper.ext.Tests.cs
> RabbitMQClient implementation

- src/CQELight/Tools/ReflectionTools.cs
> check if BaseDirectory is not null

- samples/documentation/1.HelloWorld/HelloWorld/Program.cs
- src/CQELight.Buses.InMemory/Events/InMemoryEventBus.cs
- src/CQELight/CQELight.csproj
- src/CQELight/Dispatcher/BaseDispatcher.cs
- src/CQELight/Dispatcher/Configuration/Commands/SingleCommandTypeConfiguration.cs
- src/CQELight/Dispatcher/Configuration/DispatcherConfigurationBuilder.cs
- src/CQELight/Dispatcher/Configuration/Events/SingleEventTypeConfiguration.cs
- src/CQELight/Tools/Extensions/TypeExtensions.cs
- src/CQELight/Tools/ReflectionTools.cs
> fix (white/black)list bug in bootstrapper and remove GetTypeInfo access

- src/CQELight/Dispatcher/BaseDispatcher.cs
> use typeEqualityComparer to retrieve command configuration

- src/CQELight.IoC.Autofac/AutofacScopeFactory.cs
> remove systematic call to autoregister module

- src/CQELight/Tools/ReflectionTools.cs
> fix for bad dll loading

- benchmarks/CQELight_Benchmarks/CQELight_Benchmarks.csproj
- samples/desktop/CQELight.Examples.Console/CQELight.Examples.Console.csproj
- samples/documentation/2.Geneao/Geneao/Geneao.csproj
- src/CQELight.EventStore.EFCore/CQELight.EventStore.EFCore.csproj
- tests/CQELight.EventStore.EFCore.Integration.Tests/CQELight.EventStore.EFCore.Integration.Tests.csproj
> remove dependency to SQLite/SQLServer for EF Core event store

- src/CQELight/Abstractions/Saga/Saga.cs
> remove useless reflection call

- src/CQELight.Buses.AzureServiceBus/Server/AzureServiceBusServer.cs
- src/CQELight.Buses.MSMQ/Server/MSMQServer.cs
- src/CQELight.Buses.RabbitMQ/Client/RabbitMQClientBus.cs
- src/CQELight.Buses.RabbitMQ/Server/RabbitMQServer.cs
- src/CQELight.DAL.MongoDb/Mapping/MappingInfo.cs
- src/CQELight.EventStore.MongoDb/EventStoreManager.cs
> removing all "AddDebug" to avoid depreciation warnings

- src/CQELight.IoC.Autofac/Bootstrapper.ext.cs
> add shortcut for autofac users with no custom registrations

- src/CQELight/DAL/Attributes/TableAttribute.cs
- tests/CQELight.Tests/DAL/Attributes/TableAttribute.Tests.cs
> remove dbo default value from tableAttribute

- src/CQELight.IoC.Autofac/AutofacScopeFactory.cs
- src/CQELight.IoC.Autofac/Bootstrapper.ext.cs
- tests/CQELight.IoC.Autofac.Integration.Tests/Bootstrapper.ext.Tests.cs
> allow passing scope for bootstrapping

- src/CQELight.IoC.Autofac/AutoRegisterModule.cs
- tests/CQELight.IoC.Autofac.Integration.Tests/AutofacScope.Tests.cs
> autofac auto register handlers

- src/CQELight.TestFramework/Extensions/CQELightToolBoxExtensions.cs
> implementation of test toolboxk

- src/CQELight.Buses.RabbitMQ/Client/RabbitMQEventBus.cs
- src/CQELight/Buses/Enveloppe.cs
> add new overloads for enveloppe creation

- src/CQELight.TestFramework/TestFramework/TestFrameworkActionAssertion.cs
- src/CQELight.TestFramework/TestFramework/TestFrameworkAsyncActionAssertion.cs
- src/CQELight/Dispatcher/BaseDispatcher.cs
- src/CQELight/Dispatcher/CoreDispatcher.cs
- tests/CQELight.Integration.Tests/Dispatcher/CoreDispatcher.Integration.Tests.cs
- tests/CQELight.TestFramework.Integration.Tests/TestFrameworkActionAssertionTests.cs
- tests/CQELight.TestFramework.Integration.Tests/TestFrameworkAsyncActionAssertionTests.cs
> allow to use an event for multiple event dispatching

- src/CQELight.TestFramework/BaseUnitTestClass.cs
- src/CQELight/Bootstrapping/Bootstrapper.cs
- src/CQELight/Bootstrapping/PostBootstrappingContext.cs
- src/CQELight/IoC/DIManager.cs
- tests/CQELight.Tests/Bootstrapper/Bootstrapper.Tests.cs
> post bootstrapping action

- src/CQELight/Bootstrapping/Bootstrapper.cs
- src/CQELight/Bootstrapping/BootstrapperOptions.cs
> update bootstrapper ctors

- src/CQELight.DAL.MongoDb/Bootstrapper.ext.cs
- tests/CQELight.DAL.MongoDb.Integration.Tests/Adapters/MongoDataReaderAdapter.Tests.cs
- tests/CQELight.DAL.MongoDb.Integration.Tests/Adapters/MongoDataWriterAdapter.Tests.cs
- tests/CQELight.DAL.MongoDb.Integration.Tests/MongoRepository.Tests.cs
> avoid exception when calling init on mongo dal multiple times

- docs/migrations/v1_1_1.rst
- src/CQELight.Buses.MSMQ/Bootstrapper.ext.cs
- src/CQELight.Buses.MSMQ/Client/MSMQClientBus.cs
- src/CQELight.Buses.MSMQ/Client/MSMQClientBusConfiguration.cs
- src/CQELight.Buses.MSMQ/Server/MSMQServer.cs
- src/CQELight.Buses.MSMQ/Server/MSMQServerConfiguration.cs
> deprecation of MSMQ extension

- src/CQELight.TestFramework/Logging/FakeLogger.cs
- tests/CQELight.Buses.InMemory.Integration.Tests/InMemoryEventBus.Tests.cs
> create and use fakelogger

- azure-pipelines.yml
- src/CQELight.DAL.EFCore/EFRepository.cs
- src/CQELight.EventStore.EFCore/EFEventStore.cs
> bug fixes for #394 & #395

- src/CQELight.DAL.EFCore/Bootstrapper.ext.cs
> register custom db context within ioc

- src/CQELight.IoC.Autofac/Bootstrapper.ext.cs
- src/CQELight/IoC/Enums.cs
- src/CQELight/IoC/TypeRegistration.cs
- src/CQELight/IoC/TypeRegistration`.cs
- tests/CQELight.IoC.Autofac.Integration.Tests/AutofacScope.Tests.cs
> add a parameter to type registration to defined ctor seraching politic

- src/CQELight.DAL.EFCore/Adapters/EFCoreDataWriterAdapter.cs
- src/CQELight.DAL.MongoDb/Adapters/MongoDataWriterAdapter.cs
- src/CQELight/Abstractions/DAL/Interfaces/IDataWriterAdapter.cs
- src/CQELight/DAL/RepositoryBase.cs
- tests/CQELight.DAL.MongoDb.Integration.Tests/DbEntities.cs
> delegate soft deletion to adapter level

- src/CQELight.DAL.MongoDb/Adapters/MongoDataReaderAdapter.cs
- src/CQELight.DAL.MongoDb/Adapters/MongoDataWriterAdapter.cs
- src/CQELight.DAL.MongoDb/Bootstrapper.ext.cs
- src/CQELight.DAL.MongoDb/Mapping/MappingInfo.cs
- src/CQELight.DAL.MongoDb/MongoDbContext.cs
- src/CQELight.DAL.MongoDb/MongoDbOptions.cs
- tests/CQELight.DAL.MongoDb.Integration.Tests/Adapters/MongoDataReaderAdapter.Tests.cs
- tests/CQELight.DAL.MongoDb.Integration.Tests/Adapters/MongoDataWriterAdapter.Tests.cs
- tests/CQELight.DAL.MongoDb.Integration.Tests/MongoRepository.Tests.cs
> add a way to specifiy databasename

- docs/news/v1_1.rst
Minor spelling and grammatical fixes
> Minor spelling and grammatical fixes

- src/CQELight.DAL.MongoDb/Adapters/MongoDataWriterAdapter.cs
- tests/CQELight.DAL.MongoDb.Integration.Tests/Adapters/MongoDataWriterAdapter.Tests.cs
> check if session is started before save

- src/CQELight.DAL.MongoDb/Bootstrapper.ext.cs
- src/CQELight.DAL.MongoDb/MongoDbContext.cs
> make mongo client accessible

- samples/web/CQELight_ASPNETCore3/CQELight_ASPNETCore3.csproj
- samples/web/CQELight_ASPNETCore3/Program.cs
- samples/web/CQELight_ASPNETCore3/appsettings.Development.json
- samples/web/CQELight_ASPNETCore3/appsettings.json
- src/CQELight.AspCore/CQELight.AspCore.csproj
- src/CQELight.AspCore/Extensions/ASPCoreExtensions.cs
> create an overload for configuration in configure method

- src/CQELight.DAL.MongoDb/MongoDbOptions.cs
- tests/CQELight.DAL.MongoDb.Integration.Tests/Adapters/MongoDataReaderAdapter.Tests.cs
- tests/CQELight.DAL.MongoDb.Integration.Tests/Adapters/MongoDataWriterAdapter.Tests.cs
> add a way to specify database to use for mongo

- src/CQELight.DAL.MongoDb/Bootstrapper.ext.cs
> restore serializer registration

- src/CQELight.DAL.MongoDb/Adapters/MongoDataWriterAdapter.cs
- tests/CQELight.Buses.AzureServiceBus.Integration.Tests/CQELight.Buses.AzureServiceBus.Integration.Tests.csproj
- tests/CQELight.Buses.InMemory.Integration.Tests/CQELight.Buses.InMemory.Integration.Tests.csproj
- tests/CQELight.Buses.RabbitMQ.Integration.Tests/CQELight.Buses.RabbitMQ.Integration.Tests.csproj
- tests/CQELight.DAL.EFCore.Integration.Tests/CQELight.DAL.EFCore.Integration.Tests.csproj
- tests/CQELight.DAL.MongoDb.Integration.Tests/CQELight.DAL.MongoDb.Integration.Tests.csproj
- tests/CQELight.DAL.MongoDb.Integration.Tests/RepositoryBase.Tests.cs
- tests/CQELight.EventStore.EFCore.Integration.Tests/CQELight.EventStore.EFCore.Integration.Tests.csproj
- tests/CQELight.EventStore.MongoDb.Integration.Tests/CQELight.EventStore.MongoDb.Integration.Tests.csproj
- tests/CQELight.Integration.Tests/CQELight.Integration.Tests.csproj
- tests/CQELight.IoC.Autofac.Integration.Tests/CQELight.IoC.Autofac.Integration.Tests.csproj
- tests/CQELight.IoC.Microsoft.Extensions.DependencyInjection.Tests/CQELight.IoC.Microsoft.Extensions.DependencyInjection.Tests.csproj
- tests/CQELight.MVVM.Integration.Tests/CQELight.MVVM.Integration.Tests.csproj
- tests/CQELight.MVVM.Tests/CQELight.MVVM.Tests.csproj
- tests/CQELight.TestFramework.Integration.Tests/CQELight.TestFramework.Integration.Tests.csproj
- tests/CQELight.TestFramework.Integration.Tests/Extensions/DAL/IDataReaderRepositoryExtensions.Tests.cs
- tests/CQELight.TestFramework.MVVM.Tests/CQELight.TestFramework.MVVM.Tests.csproj
- tests/CQELight.Tests/CQELight.Tests.csproj
> handle mongo max parallel connections

- src/CQELight.EventStore.EFCore/EFEventStore.cs
- tests/CQELight.EventStore.EFCore.Integration.Tests/EFEventStore.Tests.cs
> ef event store should compute sequence with aggregate type

- src/CQELight.DAL.EFCore/Bootstrapper.ext.cs
- src/CQELight.DAL.EFCore/CQELight.DAL.EFCore.csproj
- tests/CQELight.DAL.EFCore.Integration.Tests/Bootstrapper.ext.Tests.cs
> DbContext should be accessible

- src/CQELight.AspCore/CQELight.AspCore.csproj
- src/CQELight.IoC.Autofac/Bootstrapper.ext.cs
- src/CQELight.IoC.Autofac/CQELight.IoC.Autofac.csproj
- src/CQELight.IoC.Microsoft.Extensions.DependencyInjection/Bootstrapper.ext.cs
- src/CQELight.IoC.Microsoft.Extensions.DependencyInjection/CQELight.IoC.Microsoft.Extensions.DependencyInjection.csproj
- tests/CQELight.IoC.Autofac.Integration.Tests/AutofacScope.Tests.cs
- tests/CQELight.IoC.Autofac.Integration.Tests/CQELight.IoC.Autofac.Integration.Tests.csproj
- tests/CQELight.IoC.Microsoft.Extensions.DependencyInjection.Tests/CQELight.IoC.Microsoft.Extensions.DependencyInjection.Tests.csproj
- tests/CQELight.IoC.Microsoft.Extensions.DependencyInjection.Tests/MicrosoftScope.Tests.cs
> IScope should be injectable

- src/CQELight.Buses.InMemory/Commands/InMemoryCommandBus.cs
- src/CQELight.Buses.InMemory/Events/InMemoryEventBus.cs
- tests/CQELight.Buses.InMemory.Integration.Tests/CQELight.Buses.InMemory.Integration.Tests.csproj
- tests/CQELight.Buses.InMemory.Integration.Tests/InMemoryCommandBus.Tests.cs
- tests/CQELight.Buses.InMemory.Integration.Tests/InMemoryEventBus.Tests.cs
> move inmemory buses to public ctor

- src/CQELight.IoC.Autofac/AutofacScope.cs
- src/CQELight.IoC.Autofac/AutofacScopeFactory.cs
- src/CQELight.IoC.Autofac/Bootstrapper.ext.cs
- tests/CQELight.IoC.Autofac.Integration.Tests/Bootstrapper.ext.Tests.cs
> remove logger factory on asp.net core init

- src/CQELight.DAL.MongoDb/MongoDbContext.cs
> allow to publicly access database instance

- src/CQELight.AspCore/CQELight.AspCore.csproj
- src/CQELight.AspCore/Extensions/ASPCoreExtensions.cs
> fix for retrieving configuration when running in docker
